name: Ingestion Job

on:
  # schedule:
  #   - cron: "*/5 * * * *" # every 5 minutes (UTC)
  workflow_dispatch: # allow manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: poetry install --no-root

      - name: Initialize database
        run: PYTHONPATH=. poetry run python scripts/init_db.py

      - name: Run ingestion script
        run: poetry run python ingestion/ingest_openweather.py
        env:
          PYTHONPATH: .
