name: Ingest OpenWeather Data

on:
  # schedule:
  #   - cron: "*/5 * * * *" # every 5 minutes (UTC)
  workflow_dispatch: # allow manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingestion script
        env:
          PYTHONPATH: .
        run: python ingestion/ingest_openweather.py
